# Form implementation generated from reading ui file 'ui/cart_item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CartItem(object):
    def setupUi(self, CartItem):
        CartItem.setObjectName("CartItem")
        CartItem.resize(600, 120)
        CartItem.setMinimumSize(QtCore.QSize(600, 120))
        CartItem.setMaximumSize(QtCore.QSize(16777215, 120))
        CartItem.setStyleSheet("QWidget#CartItem {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ffffff, stop:1 #f8f9fa);\n"
"    border: 2px solid #e9ecef;\n"
"    border-radius: 16px;\n"
"    margin: 6px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QWidget#CartItem:hover {\n"
"    border: 2px solid #007bff;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ffffff, stop:1 #e3f2fd);\n"
"}")
        self.mainLayout = QtWidgets.QHBoxLayout(CartItem)
        self.mainLayout.setContentsMargins(12, 12, 12, 12)
        self.mainLayout.setSpacing(12)
        self.mainLayout.setObjectName("mainLayout")
        self.productImage = QtWidgets.QLabel(parent=CartItem)
        self.productImage.setMinimumSize(QtCore.QSize(100, 100))
        self.productImage.setMaximumSize(QtCore.QSize(100, 100))
        self.productImage.setStyleSheet("QLabel#productImage {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #f8f9fa, stop:1 #e9ecef);\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"    padding: 4px;\n"
"}")
        self.productImage.setText("")
        self.productImage.setScaledContents(True)
        self.productImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.productImage.setObjectName("productImage")
        self.mainLayout.addWidget(self.productImage)
        self.infoLayout = QtWidgets.QVBoxLayout()
        self.infoLayout.setSpacing(6)
        self.infoLayout.setObjectName("infoLayout")
        self.productTitle = QtWidgets.QLabel(parent=CartItem)
        self.productTitle.setStyleSheet("QLabel#productTitle {\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    color: #1a1a1a;\n"
"    line-height: 1.4;\n"
"    max-height: 60px;\n"
"}")
        self.productTitle.setWordWrap(True)
        self.productTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.productTitle.setObjectName("productTitle")
        self.infoLayout.addWidget(self.productTitle)
        self.priceLayout = QtWidgets.QHBoxLayout()
        self.priceLayout.setSpacing(8)
        self.priceLayout.setObjectName("priceLayout")
        self.productPrice = QtWidgets.QLabel(parent=CartItem)
        self.productPrice.setStyleSheet("QLabel#productPrice {\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: 700;\n"
"    color: #e74c3c;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #fff5f5, stop:1 #ffe6e6);\n"
"    padding: 4px 8px;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #ffcccc;\n"
"}")
        self.productPrice.setObjectName("productPrice")
        self.priceLayout.addWidget(self.productPrice)
        self.quantityLabel = QtWidgets.QLabel(parent=CartItem)
        self.quantityLabel.setStyleSheet("QLabel#quantityLabel {\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    color: #6c757d;\n"
"    background: #f8f9fa;\n"
"    padding: 2px 6px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #dee2e6;\n"
"}")
        self.quantityLabel.setObjectName("quantityLabel")
        self.priceLayout.addWidget(self.quantityLabel)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.priceLayout.addItem(spacerItem)
        self.infoLayout.addLayout(self.priceLayout)
        self.mainLayout.addLayout(self.infoLayout)
        self.actionLayout = QtWidgets.QVBoxLayout()
        self.actionLayout.setSpacing(8)
        self.actionLayout.setObjectName("actionLayout")
        self.removeBtn = QtWidgets.QPushButton(parent=CartItem)
        self.removeBtn.setMinimumSize(QtCore.QSize(32, 32))
        self.removeBtn.setMaximumSize(QtCore.QSize(32, 32))
        self.removeBtn.setStyleSheet("QPushButton#removeBtn {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #e74c3c, stop:1 #c0392b);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#removeBtn:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #c0392b, stop:1 #a93226);\n"
"}\n"
"\n"
"QPushButton#removeBtn:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #a93226, stop:1 #922b21);\n"
"}")
        self.removeBtn.setObjectName("removeBtn")
        self.actionLayout.addWidget(self.removeBtn)
        self.buyNowBtn = QtWidgets.QPushButton(parent=CartItem)
        self.buyNowBtn.setMinimumSize(QtCore.QSize(80, 32))
        self.buyNowBtn.setMaximumSize(QtCore.QSize(80, 32))
        self.buyNowBtn.setStyleSheet("QPushButton#buyNowBtn {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #27ae60, stop:1 #2ecc71);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 11px;\n"
"    font-weight: 600;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton#buyNowBtn:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #229954, stop:1 #27ae60);\n"
"}\n"
"\n"
"QPushButton#buyNowBtn:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #1e8449, stop:1 #229954);\n"
"}")
        self.buyNowBtn.setObjectName("buyNowBtn")
        self.actionLayout.addWidget(self.buyNowBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.actionLayout.addItem(spacerItem1)
        self.mainLayout.addLayout(self.actionLayout)

        self.retranslateUi(CartItem)
        QtCore.QMetaObject.connectSlotsByName(CartItem)

    def retranslateUi(self, CartItem):
        _translate = QtCore.QCoreApplication.translate
        CartItem.setWindowTitle(_translate("CartItem", "Cart Item"))
        self.productTitle.setText(_translate("CartItem", "Tên sản phẩm"))
        self.productPrice.setText(_translate("CartItem", "₫199K"))
        self.quantityLabel.setText(_translate("CartItem", "Số lượng: 1"))
        self.removeBtn.setText(_translate("CartItem", "×"))
        self.buyNowBtn.setText(_translate("CartItem", "Mua ngay"))
