# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 596)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(100, 330, 211, 41))
        self.btn_login.setStyleSheet(" background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 89, 102, 255), stop:1 rgba(255, 255, 255, 255)); /* Màu nền tím */\n"
"    color: black;             /* Màu chữ */\n"
"    font-size: 16px;          /* Kích thước chữ */\n"
"    font-weight: bold;        /* Chữ in đậm */\n"
"    border: none;             /* Xóa đường viền mặc định */\n"
"    border-radius: 20px;      /* Bo góc */\n"
"    padding: 10px 20px;       /* Khoảng cách bên trong */")
        self.btn_login.setObjectName("btn_login")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 90, 421, 361))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(244, 244, 244)")
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 60, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(75, 75, 75)")
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 480, 81, 21))
        self.pushButton_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius: 9px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Google__G__logo.svg.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 480, 81, 21))
        self.pushButton_3.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius: 9px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/images.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 400, 191, 31))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 14px; \n"
" border: 2px solid #ced4da;\n"
"background-color:rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(100, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font-size: 25px;          /* Kích thước chữ */\n"
"color:rgb(0, 0, 0)")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(-10, 0, 431, 91))
        self.label_13.setStyleSheet("background-color: rgb(244, 244, 244)")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(560, 300, 49, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_25 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(50, 520, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_25.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_25.setObjectName("label_25")
        self.btn_register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(260, 520, 91, 21))
        self.btn_register.setStyleSheet("color: white;             /* Màu chữ */\n"
"font-size: 16px;          /* Kích thước chữ */\n"
"font-weight: bold;        /* Chữ in đậm */\n"
"border: none;             /* Xóa đường viền mặc định */\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 190, 78)")
        self.btn_register.setObjectName("btn_register")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(0, 440, 421, 111))
        self.label_15.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 0, 431, 551))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/265b15abe358d372e8fe6cd38d982614b29e3911.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 140, 271, 161))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.horizontalLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txt_email = QtWidgets.QLineEdit(parent=self.frame_2)
        self.txt_email.setGeometry(QtCore.QRect(0, 10, 259, 57))
        self.txt_email.setMaximumSize(QtCore.QSize(2000, 2000))
        self.txt_email.setStyleSheet("background-color: #f8f9fa; /* Màu nền */\n"
"    border: 2px solid #ced4da; /* Viền */\n"
"    border-radius: 5px;       /* Bo góc */\n"
"    padding: 5px;             /* Khoảng cách bên trong */\n"
"    font-size: 14px;          /* Cỡ chữ */\n"
"    color: #495057;           /* Màu chữ */\n"
"border: 2px solid #007bff; /* Viền khi đang focus (nhấp chuột vào ô) */\n"
"    outline: none;             /* Xóa viền mặc định */")
        self.txt_email.setObjectName("txt_email")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=self.horizontalLayoutWidget)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.txt_password = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_password.setGeometry(QtCore.QRect(0, 20, 261, 51))
        self.txt_password.setStyleSheet("background-color: #f8f9fa; /* Màu nền */\n"
"    border: 2px solid #ced4da; /* Viền */\n"
"    border-radius: 5px;       /* Bo góc */\n"
"    padding: 5px;             /* Khoảng cách bên trong */\n"
"    font-size: 14px;          /* Cỡ chữ */\n"
"    color: #495057;           /* Màu chữ */\n"
"border: 2px solid #007bff; /* Viền khi đang focus (nhấp chuột vào ô) */\n"
"    outline: none;             /* Xóa viền mặc định */")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.btn_eye_p = QtWidgets.QPushButton(parent=self.frame)
        self.btn_eye_p.setGeometry(QtCore.QRect(210, 30, 51, 31))
        self.btn_eye_p.setStyleSheet("border: none;\n"
"background: none;")
        self.btn_eye_p.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/eye-slash-solid.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon2)
        self.btn_eye_p.setIconSize(QtCore.QSize(32, 32))
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 0, 101, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/ct_orange_c2c_200.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_15.raise_()
        self.label_13.raise_()
        self.label_3.raise_()
        self.btn_login.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_7.raise_()
        self.label_12.raise_()
        self.label_10.raise_()
        self.label_25.raise_()
        self.btn_register.raise_()
        self.label_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_login.setText(_translate("MainWindow", "Sign In"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Sign In Account</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Google"))
        self.pushButton_3.setText(_translate("MainWindow", "Facebook"))
        self.label_7.setText(_translate("MainWindow", "Or Create Your Account With :"))
        self.label_12.setText(_translate("MainWindow", "-Have a nice day !-"))
        self.label_25.setText(_translate("MainWindow", "You Already Have An Account?"))
        self.btn_register.setText(_translate("MainWindow", "Press Here!"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Password"))
