# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 1000)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 941, 91))
        self.label_2.setStyleSheet("background-color:rgb(255, 186, 25)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 20, 491, 51))
        self.lineEdit.setStyleSheet("border-radius: 3px")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(660, 20, 51, 51))
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Magnifying_glass_icon.svg.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.main_widget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(0, 90, 941, 1000))
        self.main_widget.setObjectName("main_widget")
        self.cart = QtWidgets.QWidget()
        self.cart.setObjectName("cart")
        self.label_18 = QtWidgets.QLabel(parent=self.cart)
        self.label_18.setGeometry(QtCore.QRect(0, 0, 941, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color:rgb(236, 236, 236)")
        self.label_18.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_18.setObjectName("label_18")
        self.label_52 = QtWidgets.QLabel(parent=self.cart)
        self.label_52.setGeometry(QtCore.QRect(-30, 30, 971, 841))
        self.label_52.setText("")
        self.label_52.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-02-09 134910.png"))
        self.label_52.setScaledContents(True)
        self.label_52.setObjectName("label_52")
        self.cart_widget = QtWidgets.QWidget(parent=self.cart)
        self.cart_widget.setGeometry(QtCore.QRect(0, 30, 941, 741))
        self.cart_widget.setObjectName("cart_widget")
        self.label_52.raise_()
        self.label_18.raise_()
        self.cart_widget.raise_()
        self.main_widget.addWidget(self.cart)
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.label_3 = QtWidgets.QLabel(parent=self.home)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 941, 671))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-02-09 134910.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.home)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 171, 131))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/pngtree-red-flash-sale-discount-logo-with-yellow-lightning-vector-png-image_7102022 (1).png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_15 = QtWidgets.QLabel(parent=self.home)
        self.label_15.setGeometry(QtCore.QRect(0, 10, 941, 611))
        self.label_15.setAutoFillBackground(False)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-02-09 134910.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.home)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 670, 941, 201))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_50 = QtWidgets.QLabel(parent=self.page_4)
        self.label_50.setGeometry(QtCore.QRect(0, 0, 941, 201))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-02-09 172159.png"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_84 = QtWidgets.QLabel(parent=self.page_5)
        self.label_84.setGeometry(QtCore.QRect(0, 0, 941, 201))
        self.label_84.setText("")
        self.label_84.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-02-09 171504.png"))
        self.label_84.setScaledContents(True)
        self.label_84.setObjectName("label_84")
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_85 = QtWidgets.QLabel(parent=self.page_6)
        self.label_85.setGeometry(QtCore.QRect(0, 0, 941, 201))
        self.label_85.setText("")
        self.label_85.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-02-09 171317.png"))
        self.label_85.setScaledContents(True)
        self.label_85.setObjectName("label_85")
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_94 = QtWidgets.QLabel(parent=self.page_7)
        self.label_94.setGeometry(QtCore.QRect(0, 0, 941, 201))
        self.label_94.setText("")
        self.label_94.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-02-09 171308.png"))
        self.label_94.setScaledContents(True)
        self.label_94.setObjectName("label_94")
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_95 = QtWidgets.QLabel(parent=self.page_8)
        self.label_95.setGeometry(QtCore.QRect(0, 0, 941, 201))
        self.label_95.setText("")
        self.label_95.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-02-09 171205.png"))
        self.label_95.setScaledContents(True)
        self.label_95.setObjectName("label_95")
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_96 = QtWidgets.QLabel(parent=self.page_9)
        self.label_96.setGeometry(QtCore.QRect(0, 0, 941, 201))
        self.label_96.setText("")
        self.label_96.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-02-09 172440.png"))
        self.label_96.setScaledContents(True)
        self.label_96.setObjectName("label_96")
        self.stackedWidget_2.addWidget(self.page_9)
        self.label_86 = QtWidgets.QLabel(parent=self.home)
        self.label_86.setGeometry(QtCore.QRect(220, 70, 661, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        self.label_86.setFont(font)
        self.label_86.setStyleSheet("background-color:rgb(236, 236, 236)")
        self.label_86.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_86.setObjectName("label_86")
        self.pro_list_widget = QtWidgets.QWidget(parent=self.home)
        self.pro_list_widget.setGeometry(QtCore.QRect(-10, 150, 951, 521))
        self.pro_list_widget.setObjectName("pro_list_widget")
        self.label_15.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.stackedWidget_2.raise_()
        self.label_86.raise_()
        self.pro_list_widget.raise_()
        self.main_widget.addWidget(self.home)
        self.detail = QtWidgets.QWidget()
        self.detail.setObjectName("detail")
        self.label_6 = QtWidgets.QLabel(parent=self.detail)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 941, 981))
        self.label_6.setStyleSheet("background-color: #f8f9fa;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.detail)
        self.label_7.setGeometry(QtCore.QRect(38, 45, 861, 401))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.bannerLabel = QtWidgets.QLabel(parent=self.detail)
        self.bannerLabel.setGeometry(QtCore.QRect(110, 100, 281, 281))
        self.bannerLabel.setStyleSheet("background-color: #ffffff;\n"
"border: 2px solid #e9ecef;\n"
"border-radius: 8px;\n"
"padding: 8px;")
        self.bannerLabel.setText("")
        self.bannerLabel.setScaledContents(True)
        self.bannerLabel.setObjectName("bannerLabel")
        self.product_info = QtWidgets.QLabel(parent=self.detail)
        self.product_info.setGeometry(QtCore.QRect(420, 100, 441, 61))
        self.product_info.setStyleSheet("background-color: transparent;\n"
"font-family: \'SF Pro Display\', \'Segoe UI\', Arial, sans-serif;\n"
"font-size: 18px;\n"
"font-weight: 700;\n"
"color: #1a1a1a;\n"
"line-height: 1.3;")
        self.product_info.setWordWrap(True)
        self.product_info.setObjectName("product_info")
        self.product_information = QtWidgets.QLabel(parent=self.detail)
        self.product_information.setGeometry(QtCore.QRect(420, 160, 441, 31))
        self.product_information.setStyleSheet("background-color: transparent;\n"
"font-family: \'SF Pro Display\', \'Segoe UI\', Arial, sans-serif;\n"
"font-size: 14px;\n"
"color: #6c757d;\n"
"line-height: 1.4;")
        self.product_information.setWordWrap(True)
        self.product_information.setObjectName("product_information")
        self.rate_star = QtWidgets.QLabel(parent=self.detail)
        self.rate_star.setGeometry(QtCore.QRect(420, 200, 81, 41))
        self.rate_star.setStyleSheet("background-color: transparent;\n"
"font-family: \'SF Pro Display\', \'Segoe UI\', Arial, sans-serif;\n"
"font-size: 14px;\n"
"color: #f39c12;\n"
"font-weight: 600;")
        self.rate_star.setObjectName("rate_star")
        self.product_price = QtWidgets.QLabel(parent=self.detail)
        self.product_price.setGeometry(QtCore.QRect(420, 260, 200, 40))
        self.product_price.setStyleSheet("background-color: transparent;\n"
"font-family: \'SF Pro Display\', \'Segoe UI\', Arial, sans-serif;\n"
"font-size: 24px;\n"
"font-weight: 700;\n"
"color: #e74c3c;\n"
"background: #fff5f5;\n"
"padding: 8px 12px;\n"
"border-radius: 6px;")
        self.product_price.setObjectName("product_price")
        self.original_price = QtWidgets.QLabel(parent=self.detail)
        self.original_price.setGeometry(QtCore.QRect(630, 270, 120, 20))
        self.original_price.setStyleSheet("background-color: transparent;\n"
"font-family: \'SF Pro Display\', \'Segoe UI\', Arial, sans-serif;\n"
"font-size: 14px;\n"
"color: #95a5a6;\n"
"text-decoration: line-through;")
        self.original_price.setObjectName("original_price")
        self.product_description = QtWidgets.QLabel(parent=self.detail)
        self.product_description.setGeometry(QtCore.QRect(420, 320, 441, 80))
        self.product_description.setStyleSheet("background-color: transparent;\n"
"font-family: \'SF Pro Display\', \'Segoe UI\', Arial, sans-serif;\n"
"font-size: 12px;\n"
"color: #495057;\n"
"line-height: 1.5;\n"
"background: #f8f9fa;\n"
"padding: 8px;\n"
"border-radius: 4px;")
        self.product_description.setWordWrap(True)
        self.product_description.setObjectName("product_description")
        self.addItemto_wantbuy = QtWidgets.QPushButton(parent=self.detail)
        self.addItemto_wantbuy.setGeometry(QtCore.QRect(420, 420, 150, 45))
        self.addItemto_wantbuy.setStyleSheet("QPushButton#addItemto_wantbuy {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ecf0f1, stop:1 #bdc3c7);\n"
"    color: #2c3e50;\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 8px;\n"
"    font-family: \'SF Pro Display\', \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton#addItemto_wantbuy:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #d5dbdb, stop:1 #aeb6bf);\n"
"    border-color: #85929e;\n"
"}\n"
"\n"
"QPushButton#addItemto_wantbuy:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #aeb6bf, stop:1 #85929e);\n"
"}")
        self.addItemto_wantbuy.setObjectName("addItemto_wantbuy")
        self.buyItemButton = QtWidgets.QPushButton(parent=self.detail)
        self.buyItemButton.setGeometry(QtCore.QRect(590, 420, 150, 45))
        self.buyItemButton.setStyleSheet("QPushButton#buyItemButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #27ae60, stop:1 #2ecc71);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-family: \'SF Pro Display\', \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton#buyItemButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #229954, stop:1 #27ae60);\n"
"    transform: scale(1.02);\n"
"}\n"
"\n"
"QPushButton#buyItemButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #1e8449, stop:1 #229954);\n"
"}")
        self.buyItemButton.setObjectName("buyItemButton")
        self.category_label = QtWidgets.QLabel(parent=self.detail)
        self.category_label.setGeometry(QtCore.QRect(420, 480, 441, 20))
        self.category_label.setStyleSheet("background-color: transparent;\n"
"font-family: \'SF Pro Display\', \'Segoe UI\', Arial, sans-serif;\n"
"font-size: 12px;\n"
"color: #6c757d;\n"
"background: #e9ecef;\n"
"padding: 4px 8px;\n"
"border-radius: 4px;")
        self.category_label.setObjectName("category_label")
        self.main_widget.addWidget(self.detail)
        self.account = QtWidgets.QWidget()
        self.account.setObjectName("account")
        self.label_41 = QtWidgets.QLabel(parent=self.account)
        self.label_41.setGeometry(QtCore.QRect(0, 0, 941, 551))
        self.label_41.setStyleSheet("background-color : rgb(222, 222, 222);\n"
"")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.label_75 = QtWidgets.QLabel(parent=self.account)
        self.label_75.setGeometry(QtCore.QRect(10, 10, 341, 241))
        self.label_75.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius : 10px")
        self.label_75.setText("")
        self.label_75.setObjectName("label_75")
        self.user_background_image = QtWidgets.QLabel(parent=self.account)
        self.user_background_image.setGeometry(QtCore.QRect(10, 10, 341, 91))
        self.user_background_image.setStyleSheet("background-color: rgb(234, 234, 234);\n"
"border-radius: 10px")
        self.user_background_image.setText("")
        self.user_background_image.setObjectName("user_background_image")
        self.label_78 = QtWidgets.QLabel(parent=self.account)
        self.label_78.setGeometry(QtCore.QRect(20, 210, 16, 16))
        self.label_78.setText("")
        self.label_78.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/calendar-solid.svg"))
        self.label_78.setScaledContents(True)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(parent=self.account)
        self.label_79.setGeometry(QtCore.QRect(40, 210, 91, 16))
        self.label_79.setObjectName("label_79")
        self.label_82 = QtWidgets.QLabel(parent=self.account)
        self.label_82.setGeometry(QtCore.QRect(20, 170, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.label_80 = QtWidgets.QLabel(parent=self.account)
        self.label_80.setGeometry(QtCore.QRect(360, 10, 571, 531))
        self.label_80.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius : 10px")
        self.label_80.setText("")
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(parent=self.account)
        self.label_81.setGeometry(QtCore.QRect(420, 90, 421, 241))
        self.label_81.setText("")
        self.label_81.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Screenshot 2025-03-05 230622.png"))
        self.label_81.setIndent(5)
        self.label_81.setObjectName("label_81")
        self.label_83 = QtWidgets.QLabel(parent=self.account)
        self.label_83.setGeometry(QtCore.QRect(510, 340, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.up_item_for_sale = QtWidgets.QPushButton(parent=self.account)
        self.up_item_for_sale.setGeometry(QtCore.QRect(570, 380, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.up_item_for_sale.setFont(font)
        self.up_item_for_sale.setStyleSheet("")
        self.up_item_for_sale.setObjectName("up_item_for_sale")
        self.label_87 = QtWidgets.QLabel(parent=self.account)
        self.label_87.setGeometry(QtCore.QRect(10, 260, 341, 281))
        self.label_87.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius : 10px")
        self.label_87.setText("")
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(parent=self.account)
        self.label_88.setGeometry(QtCore.QRect(20, 260, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_88.setFont(font)
        self.label_88.setObjectName("label_88")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.account)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 290, 181, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_name = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txt_name.setMaximumSize(QtCore.QSize(175, 50))
        self.txt_name.setStyleSheet("background-color: #f8f9fa; /* Màu nền */\n"
"    border: 2px solid #ced4da; /* Viền */\n"
"    border-radius: 5px;       /* Bo góc */\n"
"    padding: 5px;             /* Khoảng cách bên trong */\n"
"    font-size: 14px;          /* Cỡ chữ */\n"
"    color: #495057;           /* Màu chữ */\n"
"border: 2px solid #007bff; /* Viền khi đang focus (nhấp chuột vào ô) */\n"
"    outline: none;             /* Xóa viền mặc định */")
        self.txt_name.setObjectName("txt_name")
        self.verticalLayout.addWidget(self.txt_name)
        self.txt_age = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txt_age.setMaximumSize(QtCore.QSize(175, 40))
        self.txt_age.setStyleSheet("background-color: #f8f9fa; /* Màu nền */\n"
"    border: 2px solid #ced4da; /* Viền */\n"
"    border-radius: 5px;       /* Bo góc */\n"
"    padding: 5px;             /* Khoảng cách bên trong */\n"
"    font-size: 14px;          /* Cỡ chữ */\n"
"    color: #495057;           /* Màu chữ */\n"
"border: 2px solid #007bff; /* Viền khi đang focus (nhấp chuột vào ô) */\n"
"    outline: none;             /* Xóa viền mặc định */")
        self.txt_age.setObjectName("txt_age")
        self.verticalLayout.addWidget(self.txt_age)
        self.txt_email = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txt_email.setMaximumSize(QtCore.QSize(175, 40))
        self.txt_email.setStyleSheet("background-color: #f8f9fa; /* Màu nền */\n"
"    border: 2px solid #ced4da; /* Viền */\n"
"    border-radius: 5px;       /* Bo góc */\n"
"    padding: 5px;             /* Khoảng cách bên trong */\n"
"    font-size: 14px;          /* Cỡ chữ */\n"
"    color: #495057;           /* Màu chữ */\n"
"border: 2px solid #007bff; /* Viền khi đang focus (nhấp chuột vào ô) */\n"
"    outline: none;             /* Xóa viền mặc định */")
        self.txt_email.setObjectName("txt_email")
        self.verticalLayout.addWidget(self.txt_email)
        self.txt_birthday = QtWidgets.QDateEdit(parent=self.verticalLayoutWidget)
        self.txt_birthday.setMaximumSize(QtCore.QSize(175, 16777215))
        self.txt_birthday.setObjectName("txt_birthday")
        self.verticalLayout.addWidget(self.txt_birthday)
        self.frame = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame.setMaximumSize(QtCore.QSize(175, 75))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 101, 20))
        self.label_5.setObjectName("label_5")
        self.cb_gender = QtWidgets.QComboBox(parent=self.frame)
        self.cb_gender.setGeometry(QtCore.QRect(0, 20, 171, 41))
        self.cb_gender.setMaximumSize(QtCore.QSize(185, 16777215))
        self.cb_gender.setEditable(True)
        self.cb_gender.setObjectName("cb_gender")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.verticalLayout.addWidget(self.frame)
        self.update_user = QtWidgets.QPushButton(parent=self.account)
        self.update_user.setGeometry(QtCore.QRect(210, 380, 121, 41))
        self.update_user.setObjectName("update_user")
        self.change_background_image = QtWidgets.QPushButton(parent=self.account)
        self.change_background_image.setGeometry(QtCore.QRect(310, 20, 31, 24))
        self.change_background_image.setStyleSheet("border-radius:1px")
        self.change_background_image.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/camera-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.change_background_image.setIcon(icon1)
        self.change_background_image.setIconSize(QtCore.QSize(20, 20))
        self.change_background_image.setObjectName("change_background_image")
        self.frame_2 = QtWidgets.QFrame(parent=self.account)
        self.frame_2.setGeometry(QtCore.QRect(20, 50, 111, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_avatar = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_avatar.setGeometry(QtCore.QRect(80, 90, 31, 24))
        self.btn_avatar.setStyleSheet("border-radius:1px")
        self.btn_avatar.setText("")
        self.btn_avatar.setIcon(icon1)
        self.btn_avatar.setIconSize(QtCore.QSize(20, 20))
        self.btn_avatar.setObjectName("btn_avatar")
        self.image_button = QtWidgets.QLabel(parent=self.frame_2)
        self.image_button.setGeometry(QtCore.QRect(0, 0, 111, 111))
        self.image_button.setText("")
        self.image_button.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/user imgae.svg"))
        self.image_button.setScaledContents(True)
        self.image_button.setObjectName("image_button")
        self.image_button.raise_()
        self.btn_avatar.raise_()
        self.main_widget.addWidget(self.account)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, -1, 160, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_nav_home = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_nav_home.setStyleSheet("background: none;\n"
"    border: none;\n"
"    padding: 0;\n"
"    cursor: pointer;")
        self.btn_nav_home.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/house-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nav_home.setIcon(icon2)
        self.btn_nav_home.setIconSize(QtCore.QSize(51, 51))
        self.btn_nav_home.setObjectName("btn_nav_home")
        self.horizontalLayout_2.addWidget(self.btn_nav_home)
        self.btn_cart = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_cart.setStyleSheet("background: none;\n"
"    border: none;\n"
"    padding: 0;\n"
"    cursor: pointer;")
        self.btn_cart.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/cart-shopping-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_cart.setIcon(icon3)
        self.btn_cart.setIconSize(QtCore.QSize(51, 51))
        self.btn_cart.setObjectName("btn_cart")
        self.horizontalLayout_2.addWidget(self.btn_cart)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(750, -1, 160, 91))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_nav_account = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.btn_nav_account.setStyleSheet("background: none;\n"
"    border: none;\n"
"    padding: 0;\n"
"    cursor: pointer;")
        self.btn_nav_account.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/circle-user-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nav_account.setIcon(icon4)
        self.btn_nav_account.setIconSize(QtCore.QSize(51, 51))
        self.btn_nav_account.setObjectName("btn_nav_account")
        self.horizontalLayout_3.addWidget(self.btn_nav_account)
        self.btn_nav_settings = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.btn_nav_settings.setStyleSheet("background: none;\n"
"    border: none;\n"
"    padding: 0;\n"
"    cursor: pointer;")
        self.btn_nav_settings.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/gear-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nav_settings.setIcon(icon5)
        self.btn_nav_settings.setIconSize(QtCore.QSize(51, 51))
        self.btn_nav_settings.setObjectName("btn_nav_settings")
        self.horizontalLayout_3.addWidget(self.btn_nav_settings)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_widget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Tìm Kiếm Sản Phẩm Trên Hari Shop"))
        self.label_18.setText(_translate("MainWindow", "                                                                 Giỏ hàng"))
        self.label_86.setText(_translate("MainWindow", " Flash Sale, Nơi Mọi Người Mua Sắm Mặt Hàng Với Giá Rẻ"))
        self.product_info.setText(_translate("MainWindow", "Tên sản phẩm"))
        self.product_information.setText(_translate("MainWindow", "Thông tin sản phẩm"))
        self.rate_star.setText(_translate("MainWindow", "⭐⭐⭐⭐⭐ 5.0"))
        self.product_price.setText(_translate("MainWindow", "₫199K"))
        self.original_price.setText(_translate("MainWindow", "₫299K"))
        self.product_description.setText(_translate("MainWindow", "Mô tả chi tiết sản phẩm sẽ hiển thị ở đây..."))
        self.addItemto_wantbuy.setText(_translate("MainWindow", "🛒 Thêm vào giỏ"))
        self.buyItemButton.setText(_translate("MainWindow", "💳 Mua ngay"))
        self.category_label.setText(_translate("MainWindow", "Danh mục: Xe cộ - Ô tô"))
        self.label_79.setText(_translate("MainWindow", "Ngày Tham Gia :"))
        self.label_82.setText(_translate("MainWindow", "Name"))
        self.label_83.setText(_translate("MainWindow", "Bạn chưa có tin đăng nào cả"))
        self.up_item_for_sale.setText(_translate("MainWindow", "Đăng Tin Ngay"))
        self.label_88.setText(_translate("MainWindow", "Cập Nhật Thông Tin Người Dùng"))
        self.txt_name.setPlaceholderText(_translate("MainWindow", "Tên/Name"))
        self.txt_age.setPlaceholderText(_translate("MainWindow", "Tuổi/Age"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Đổi Email"))
        self.label_5.setText(_translate("MainWindow", "Giới Tính/Gender"))
        self.cb_gender.setItemText(0, _translate("MainWindow", "Không Tiết Lộ"))
        self.cb_gender.setItemText(1, _translate("MainWindow", "Nam"))
        self.cb_gender.setItemText(2, _translate("MainWindow", "Nữ"))
        self.cb_gender.setItemText(3, _translate("MainWindow", "Khác"))
        self.update_user.setText(_translate("MainWindow", "Bấm Để Cập Nhật"))
