# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/signup.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 594)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 320, 271, 41))
        self.pushButton.setStyleSheet(" background-color: #8a2be2; /* Màu nền tím */\n"
"    color: white;             /* Màu chữ */\n"
"    font-size: 16px;          /* Kích thước chữ */\n"
"    font-weight: bold;        /* Chữ in đậm */\n"
"    border: none;             /* Xóa đường viền mặc định */\n"
"    border-radius: 20px;      /* Bo góc */\n"
"    padding: 10px 20px;       /* Khoảng cách bên trong */\n"
"    background-color: #6a1bbd; /* Màu nền khi hover */\n"
"    background-color: #4e1391; /* Màu nền khi nhấn */\n"
" ")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, 470, 421, 101))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 411, 471))
        self.label_3.setStyleSheet("background-color: rgb(244, 244, 244)")
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 480, 81, 21))
        self.pushButton_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius: 9px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/Google__G__logo.svg.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 480, 81, 21))
        self.pushButton_3.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius: 9px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/images.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(150, 420, 101, 31))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 14px; \n"
" border: 2px solid #ced4da;")
        self.label_7.setObjectName("label_7")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(120, 380, 171, 21))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 520, 91, 21))
        self.pushButton_5.setStyleSheet("color: white;             /* Màu chữ */\n"
"font-size: 16px;          /* Kích thước chữ */\n"
"font-weight: bold;        /* Chữ in đậm */\n"
"border: none;             /* Xóa đường viền mặc định */\n"
"border-radius: 20px;\n"
"background-color: rgb(0, 0, 255)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, -10, 221, 51))
        self.label_6.setStyleSheet("font-size: 20px;          /* Kích thước chữ */\n"
"    font-weight: Arial;\n"
"color:rgb(0, 0, 0)")
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(40, 40, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("font-size: 25px;          /* Kích thước chữ */\n"
"color:rgb(0, 0, 0)")
        self.label_15.setObjectName("label_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 200, 251, 41))
        self.lineEdit_3.setStyleSheet("background-color: #f8f9fa; /* Màu nền */\n"
"    border: 2px solid #ced4da; /* Viền */\n"
"    border-radius: 5px;       /* Bo góc */\n"
"    padding: 5px;             /* Khoảng cách bên trong */\n"
"    font-size: 14px;          /* Cỡ chữ */\n"
"    color: #495057;           /* Màu chữ */\n"
"border: 2px solid #007bff; /* Viền khi đang focus (nhấp chuột vào ô) */\n"
"    outline: none;             /* Xóa viền mặc định */")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 140, 251, 41))
        self.lineEdit_4.setStyleSheet("background-color: #f8f9fa; /* Màu nền */\n"
"    border: 2px solid #ced4da; /* Viền */\n"
"    border-radius: 5px;       /* Bo góc */\n"
"    padding: 5px;             /* Khoảng cách bên trong */\n"
"    font-size: 14px;          /* Cỡ chữ */\n"
"    color: #495057;           /* Màu chữ */\n"
"border: 2px solid #007bff; /* Viền khi đang focus (nhấp chuột vào ô) */\n"
"    outline: none;             /* Xóa viền mặc định */")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_26 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(300, 210, 21, 21))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/download (1).jpg"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 80, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(75, 75, 75)")
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 260, 251, 41))
        self.lineEdit_5.setStyleSheet("background-color: #f8f9fa; /* Màu nền */\n"
"    border: 2px solid #ced4da; /* Viền */\n"
"    border-radius: 5px;       /* Bo góc */\n"
"    padding: 5px;             /* Khoảng cách bên trong */\n"
"    font-size: 14px;          /* Cỡ chữ */\n"
"    color: #495057;           /* Màu chữ */\n"
"border: 2px solid #007bff; /* Viền khi đang focus (nhấp chuột vào ô) */\n"
"    outline: none;             /* Xóa viền mặc định */")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_27 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(300, 270, 21, 21))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/download (1).jpg"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 0, 431, 551))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/265b15abe358d372e8fe6cd38d982614b29e3911.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 520, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(38, 145, 31, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/at-solid.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(38, 205, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/key-solid.svg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(38, 265, 31, 31))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/BaoChau/python-app/ui/../img/check-solid.svg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_7.raise_()
        self.checkBox.raise_()
        self.pushButton_5.raise_()
        self.label_6.raise_()
        self.label_15.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.label_26.raise_()
        self.label_8.raise_()
        self.lineEdit_5.raise_()
        self.label_27.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", " Click Here To Create Account"))
        self.pushButton_2.setText(_translate("MainWindow", "Google"))
        self.pushButton_3.setText(_translate("MainWindow", "Facebook"))
        self.label_7.setText(_translate("MainWindow", "Or Create By:"))
        self.checkBox.setText(_translate("MainWindow", "I agree to the terms of use"))
        self.pushButton_5.setText(_translate("MainWindow", "Click Here!"))
        self.label_6.setText(_translate("MainWindow", "      Hari Shop Online"))
        self.label_15.setText(_translate("MainWindow", "-Welcome, Have a nice day !-"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Username"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">Sign Up Account</span></p></body></html>"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.label.setText(_translate("MainWindow", "You Already Have An Account?"))
